# baseURL = 'https://ultraculture.ru'
relativeURLs = true
languageCode = 'ru'
title = "«Ультра.Культура» Издательство Ильи Кормильцева"
theme = 'book'
disablePathToLower = true

[markup.tableOfContents]
  startLevel = 2

[params]
# BookMenuBundle = '/menu'
BookToC = true
BookSection = 'docs'
BookComments = false
